server:
  port: 8083

spring:
  application:
    name: ai-agent-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/stock_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:12345678}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ai-agent-group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.lakshya.aiagent.model.StockEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

gemini:
  api:
    key: ${GEMINI_API_KEY}
news:
  api:
    key: ${NEWS_API_KEY}

jwt:
  secret: mR9qZ2xWQnV4T3JkTnY1cHhFZ0s4QmF5YzJQd2RZa1pQeE5uT1VtWkRrPQ==
  expiration: 3600000

logging:
  level:
    root: INFO
    com.lakshya.aiagent: DEBUG
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always