
import { useRecommendations } from '../hooks/queries';
import { Layout } from '../components/layout/Layout';
import { Card } from '../components/ui/Core';
import { RecommendationBadge, ConfidenceRing } from '../components/ui/DomainComponents';
import { formatTime } from '../utils/formatters';
import { motion, AnimatePresence } from 'framer-motion';

export const Feed = () => {
  // Poll every 5s for the live feed
  const { data, isLoading } = useRecommendations(undefined, 0, 20, 'timestamp', 'desc', 5000);
  const recs = data?.content || [];

  return (
    <Layout>
      <div className="p-6 max-w-4xl mx-auto">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-light text-white tracking-tight">Live Intelligence Feed</h1>
            <p className="text-indigo-200/60 mt-2">Real-time alerts generated by MarketPulse AI.</p>
          </div>
          <div className="flex h-3 w-3 relative">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-buy opacity-75"></span>
            <span className="relative inline-flex rounded-full h-3 w-3 bg-buy"></span>
          </div>
        </div>

        {isLoading && recs.length === 0 ? (
          <div className="text-outline_variant text-center py-12">Establishing feed connection...</div>
        ) : (
          <div className="space-y-4">
            <AnimatePresence initial={false}>
              {recs.map((rec) => (
                <motion.div
                  key={rec.id}
                  initial={{ opacity: 0, y: -20, scale: 0.95 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95, transition: { duration: 0.2 } }}
                  transition={{ duration: 0.4, type: 'spring', bounce: 0.3 }}
                >
                  <Card className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-l-4" style={{
                    borderLeftColor: rec.recommendation === 'BUY' ? '#22c55e' : rec.recommendation === 'SELL' ? '#ef4444' : '#f59e0b'
                  }}>
                    <div className="flex items-center gap-6">
                      <div className="flex flex-col">
                        <span className="text-xs text-outline_variant mb-1">{formatTime(rec.timestamp)}</span>
                        <span className="text-2xl font-bold text-white tracking-tight">{rec.symbol}</span>
                      </div>
                      <RecommendationBadge type={rec.recommendation} />
                    </div>
                    
                    <div className="flex-1 text-sm text-indigo-100/80 px-4">
                      {rec.reason}
                    </div>

                    <div className="flex items-center gap-6">
                      <div className="flex flex-col text-right">
                        <span className="text-xs text-outline_variant mb-1">Sentiment</span>
                        <span className="font-semibold text-indigo-50">{rec.sentiment}</span>
                      </div>
                      <div className="flex flex-col items-center">
                        <ConfidenceRing value={rec.confidence} />
                      </div>
                    </div>
                  </Card>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}
      </div>
    </Layout>
  );
};
